language: r

env:
  global:
    - secure: "mnw4y2Jw0pOl2pyS4SWz4GvssBlshr9dewX+9pqLecw99QOy8O0u5CsP6F2WY8SXINEJWhqTZWOpGjAh2M2KSjGncRxaz1TGaGM4d1fXMCpV14s7GTXUni/8Pam8LAA/b0sPqsx92t7vPhVTXp7Py1WC8r8mwaVMX+6BTlX0H914hFE8pKEGt2g4Xt+To1mMsuFrnoeh8omGiYPP/UTAexC6q5uIDF7lfTEUM/NGOi6cSmTYoocYOBhVyjrqZbCKLpHpwNC3LldmMYNMYKEk7nx7/xhYLK5wxJKjzyCrIPGiymFiBEeEU2ZTkey2y9s4M3DeVz/vXT84ZWOlZ47vIy4QLs565VSgSJ8wtI5htU8v1vi1o88V/+HHTtOcSepxASHE0FtFw2DSNrh2rc8d+P6kfBoZubPo80CM0GUFDerlDespbiN5Grm9xNgIJfRDh9LSXzj7CB8mGXn2pc5BY3VJV5bVGDydFJGj3TU6MmfGOLwP8pPGql5sIqi3j6VYgLe8tvTl0+1k2PaZib2wc8SvX0l4TTfTIvsRikgrga+d73AZuCDrz8y1UmW+KzTq/MewcQ2T/8KC3s32/U6+Xk0m3W4mH38QZM7y3IC7n+Wb2SFMIx7Kp5/xQ2clcivGddF0PxuHjeAntl6cbMvaF1xwHc4mBJXIMc8ae7BQN30="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh