# Data transformation

```{r include=FALSE}
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("nycflights13")) install.packages("nycflights13")
library(nycflights13)
library(tidyverse)
```

## 5.2.4 Exercises {-}

1. Find all flights that

    1. Had an arrival delay of two or more hours
    1. Flew to Houston (`IAH` or `HOU`)
    1. Were operated by United, American, or Delta
    1. Departed in summer (July, August, and September)
    1. Arrived more than two hours late, but didn't leave late
    1. Were delayed by at least an hour, but made up over 30 minutes in flight
    1. Departed between midnight and 6am (inclusive)






2.  Another useful dplyr filtering helper is `between()`. What does it do?
    Can you use it to simplify the code needed to answer the previous 
    challenges?

3.  How many flights have a missing `dep_time`? What other variables are 
    missing? What might these rows represent?

4.  Why is `NA ^ 0` not missing? Why is `NA | TRUE` not missing?
    Why is `FALSE & NA` not missing? Can you figure out the general
    rule?  (`NA * 0` is a tricky counterexample!)

